=== kajal-0101/webtech-lab/cia2/MerchandiseDetails.dtd
<!DOCTYPE merchandise
[
<!ELEMENT merchandise(order) *>
<!ELEMENT order (userid, phone, email, address, pincode, city, state, country, sport, gear, merchandise, quantity, orderdate, payment)>
<!ELEMENT userid (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT sport (#PCDATA)>
<!ELEMENT gear (#PCDATA)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!Element active_score (#PCDATA)>
<!ELEMENT orderdate (#PCDATA)>
<!ELEMENT payment (#PCDATA)>
]>

=== kajal-0101/webtech-lab/shopper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE merchandise SYSTEM "MerchandiseDetails.dtd"> -->
<?xml-stylesheet type = "text/xsl" href = "shopper.xsl"?>
<merchandise xmlns:xlink="http://www.w3.org/1999/xlink">
	<order id="1">
		<userid membership="platinium">SW001</userid>
		<name>Kajal</name>
		<city>Kolkata</city>
		<state>West Bengal</state>
		<sport>Rowing</sport>
		<gear>Team</gear>
		<item>Sweatshirt</item>
		<quantity>8</quantity>
		<active_score>4.5</active_score>
		<orderdate>02-08-2020</orderdate>
		<payment>UPI</payment>
	</order>

	<order id="2">
		<userid membership="silver">SW002</userid>
		<name>Nishi</name>
		<city>Surat</city>
		<state>Gujarat</state>
		<sport>Basketball</sport>
		<gear>Team</gear>
		<item>Sippers</item>
		<quantity>11</quantity>
		<active_score>2.8</active_score>
		<orderdate>06-08-2020</orderdate>
		<payment>Debit Card</payment>
	</order>

	<order id="3">
		<userid membership="gold">SW003</userid>
		<name>Sarika</name>
		<city>Bangalore</city>
		<state>Karnataka</state>
		<sport>Swimming</sport>
		<gear>Personal</gear>
		<item>Personalised cap</item>
		<quantity>1</quantity>
		<active_score>4.3</active_score>
		<orderdate>09-08-2020</orderdate>
		<payment>Debit Card</payment>
	</order>

	<order id="4">
		<userid membership="gold">SW004</userid>
		<name>Sashank</name>
		<city>Patna</city>
		<state>Bihar</state>
		<sport>Mountaineering</sport>
		<gear>Personal</gear>
		<item>Rucksack</item>
		<quantity>1</quantity>
		<active_score>3.9</active_score>
		<orderdate>10-08-2020</orderdate>
		<payment>UPI</payment>
	</order>

	<order id="5">
		<userid membership="platinium">SW005</userid>
		<name>Pinto</name>
		<city>Bangalore</city>
		<state>Karnataka</state>
		<sport>Biking</sport>
		<gear>Personal</gear>
		<item>Personalised Jacket</item>
		<quantity>1</quantity>
		<active_score>4.1</active_score>
		<orderdate>12-08-2020</orderdate>
		<payment>UPI</payment>
	</order>
</merchandise>
